spring:
  application:
    name: PetrService
  cloud:
    zookeeper:
      connect-string: 35.247.47.255:2181
      discovery:
        enabled: true
  datasource:
    url: postgres://postgres:postgrespw@postgres:5432
    username: postgres
    password: postgrespw
    driver-class-name: org.postgresql.Driver
