spring:
  application:
    name: PetrService
  cloud:
    zookeeper:
      connect-string: 35.247.47.255:2181
      discovery:
        enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:demo;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
